#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import deasciifier

class Deasciify:
    """
    This is the commandline utility for deasciification.

    Example usage:

    $ echo "Opusmegi cagristiran catirtilar." | python deasciify.py
    $ cat somefile.txt | python deasciify
    """


    def deasciify(self):
        string = sys.stdin.read()
        dea = deasciifier.Deasciifier(string.decode("utf-8"))
        result = dea.convert_to_turkish()
        sys.stdout.write(result.encode("utf-8"))

if __name__ == "__main__":
    d = Deasciify()
    d.deasciify()
